Provide an entry page for GraalVM CE container images in GitHub Registry
graalvm/container pull request #32
Opened 2021-11-25 14:06 UTC by olyagpl

2021-11-25 16:22 UTC, ezzarghili requested changes

2021-11-25 16:48 UTC, olyagpl commented on README.md
> +|--------------|----------------------------------------------------------------------------------------------------------------------------------------------|
Good to know!  My rewrote:
_Some images are `gu`-based (containing the [GraalVM Updater](https://github.com/oracle/graal/blob/master/docs/reference-manual/graalvm-updater.md) tool), some are RPM-based._

2021-11-25 16:48 UTC, olyagpl commented on README.md
> +It is recommended to use the most specific tag, e.g., `java17-21.3.0` or `java17-21.3.0-b1`, where the `_b1` means the image required a patch and was rebuilt.
_It is recommended to use the most specific tag, e.g., `java17-21.3.0` or `java17-21.3.0-b1`, where the 
`-b1` means the image required a patch and this specific build will never change._

2021-11-25 16:48 UTC, olyagpl commented on README.md
> +The images are tagged with the format `ghcr.io/OWNER/IMAGE_NAME:version`, where `OWNER` is the repository name, `graalvm` in our case, and `IMAGE_NAME` is the package name.
_The images are tagged with the format `ghcr.io/graalvm/IMAGE_NAME:version`, where `IMAGE_NAME` is a package name._

I would explain just why image name = package name, what you see on https://github.com/orgs/graalvm/packages?repo_name=container.

2021-11-25 16:54 UTC, olyagpl commented on README.md
> +| truffleruby  | GraalVM Community compact image with the Ruby runtime.                                                                                       |
Done

2021-11-25 17:00 UTC, olyagpl commented on README.md
> +
Thanks!

2021-11-30 23:53 UTC, ezzarghili approved these changes

2021-12-02 20:01 UTC, shaunsmith requested changes

2021-12-03 07:16 UTC, olyagpl commented on README.md
> +# GraalVM Community Container Images
I tried to be less wordy, but according to our guidelines, we indeed should use a full name, "GraalVM Community Edition".

2021-12-03 07:24 UTC, olyagpl commented on README.md
> +You can pull a package by name or by name and version tag.
Got it

2021-12-13 14:28 UTC, ezzarghili commented on README.md
> +| jdk          | GraalVM Community compact JDK container image without additional features.                                                                                 | RMP-based |
I agree.
For instance:

> JDK: A size compact GraalVM Community container image with the GraalVM JDK [rpm](https://yum.oracle.com/repo/OracleLinux/OL7/graalvm/community/x86_64/index.html) pre-installed.


maybe use a reference here such as  RMP-based (1)

> (1) Bases on GraalVM components rpms available for [Oracle Linux 7](https://yum.oracle.com/repo/OracleLinux/OL7/graalvm/community/x86_64/index.html)  or  [Oracle Linux 8](https://yum.oracle.com/repo/OracleLinux/OL8/graalvm/community/x86_64/index.html),  similar to any other available packages, you can install these packages using `yum` on OL7 or `microdnf` on the OL8 based images.

2021-12-13 14:29 UTC, ezzarghili commented on README.md
> +| jdk          | GraalVM Community compact JDK container image without additional features.                                                                                 | RMP-based |
@olyagpl I will leave it to you to find better wording for this.

2021-12-13 16:51 UTC, olyagpl commented on README.md
> +| jdk          | GraalVM Community compact JDK container image without additional features.                                                                                 | RMP-based |
@shaunsmith, please review https://github.com/graalvm/container/pull/32/commits/7feeba41151d71a395262984efd704869f719e12

2021-12-20 12:54 UTC, merged